name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  tflite: ^1.1.2

  image_picker_web: ^2.0.7 # Correct placement of image_picker
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  image_picker: ^0.8.7+3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt
